name: Build and Save Docker Image
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Image
        run: docker build -t mi-docker-web .
      - name: Archive Image
        run: docker save -o mi_web.tar mi-docker-web
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-tar-image
          path: mi_docker.ta
